# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(684, 403)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.full_layout = QtWidgets.QHBoxLayout()
        self.full_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.full_layout.setContentsMargins(-1, -1, -1, 0)
        self.full_layout.setSpacing(6)
        self.full_layout.setObjectName("full_layout")
        self.game_menu = QtWidgets.QListWidget(self.centralwidget)
        self.game_menu.setObjectName("game_menu")
        self.full_layout.addWidget(self.game_menu)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.full_layout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.game_view = QtWidgets.QVBoxLayout()
        self.game_view.setObjectName("game_view")
        self.title_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.title_label.setObjectName("title_label")
        self.game_view.addWidget(self.title_label)
        self.image_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.image_label.setObjectName("image_label")
        self.game_view.addWidget(self.image_label)
        self.progress_bar = QtWidgets.QProgressBar(self.widget)
        self.progress_bar.setEnabled(True)
        self.progress_bar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.game_view.addWidget(self.progress_bar)
        self.patch_button = QtWidgets.QPushButton(self.widget)
        self.patch_button.setMinimumSize(QtCore.QSize(0, 40))
        self.patch_button.setObjectName("patch_button")
        self.game_view.addWidget(self.patch_button)
        self.horizontalLayout_2.addLayout(self.game_view)
        self.full_layout.addWidget(self.widget)
        self.full_layout.setStretch(0, 1)
        self.full_layout.setStretch(2, 3)
        self.gridLayout_2.addLayout(self.full_layout, 0, 0, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.actiontest = QtWidgets.QAction(main_window)
        self.actiontest.setCheckable(False)
        self.actiontest.setEnabled(True)
        self.actiontest.setObjectName("actiontest")

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.game_menu, self.patch_button)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "SiyarbekirsPatcher"))
        self.title_label.setText(_translate("main_window", "Siyarbekir\'s Game-Patcher"))
        self.patch_button.setText(_translate("main_window", "Patch!"))
        self.actiontest.setText(_translate("main_window", "test"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
